### ISSUE TITLE
Telegram do not match system theme appearance 

### ISSUE THREAD

**Issue by jackyfox** [overtake/TelegramSwift#764]
Hello!

Noticed after recent update that Telegram window do not follow system theme appearance (light mode, dark mode).
If I select System Color Theme at Telegram settings it is always Dark Theme shows up even if I manually switch theme to light in MacOS System Preferences.

<img width="1440" alt="Screenshot 2022-04-18 at 10 46 24" src="https://user-images.githubusercontent.com/693161/163800650-9f25f00a-35f6-48a0-9fdf-d6c36cdb8ba8.png">

Telegram 8.6.228556 AppStore version
MacOS Monterey 12.3.1 (21E258) on MacBook Pro (mid 2020, Intel, 4 ports)

**Comment by FaroukZeino** [comment]
Any update on this?

**Comment by kambala-decapitator** [comment]
still the case in 8.7.1.229827 AppStore

**Comment by visarea** [comment]
Seems to still persist as of 8.9.234962 AppStore.

**Comment by friebetill** [comment]
It works for me, but the setting is unintuitive. You have to set the Auto-Night-Mode to System:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/10923085/192501543-0ff9e1f5-3fe5-48cf-ad80-6e4bc09c3f13.png">

**Comment by jackyfox** [comment]
Still the same for me.
MacOS 12.6 (21G115).
Telegram 9.0.1.237033 Stable

<img width="1440" alt="Screenshot 2022-09-27 at 15 43 36" src="https://user-images.githubusercontent.com/693161/192529678-89bdf8f5-4252-49c8-973c-212fae2cb666.png">

**Comment by friebetill** [comment]
At the bottom is the AUTO-NIGHT MODE setting, can you set that to System and then let me know if it works?

**Comment by jackyfox** [comment]
> At the bottom is the AUTO-NIGHT MODE setting, can you set that to System and then let me know if it works?

With Auto-Night Mode it is works as expected. Now telegram switches the theme according to the system settings.
But I guess it's a bit counterintuitive.

Why Telegram's “System” theme is dark by default? =)

**Comment by Write** [comment]
I never could make this feature work, either with auto-night mode following System or Scheduled, when I wake up my computer and there was a change during sleep, Telegram NEVER ever changed automatically, I always had to Cmd+Q the app and reopen it. It drives me crazy. Any idea?

**Comment by kambala-decapitator** [comment]
on app start it doesn't pick system mode though. Turned off Mac in dark mode, booted it in light mode, launched Telegram - it was dark. In settings I had auto-night=system and Dark Mode toggle was on.

**Comment by panosru** [comment]
I still face both Scenario A and B, as I mentioned in #815, at version 9.0.1.237033 Stable and macOS 12.6 (Auto-Nigh Mode is set to System).

**Comment by wilky761** [comment]
Is this going to be fixed? I have this issue too, and it's irritating. When you have to relaunch Telegram just to get it to match your mac (if in light mode or dark mode).

**Comment by Write** [comment]
lol yeah that's crazy :(

**Comment by xezrunner** [comment]
> on app start it doesn't pick system mode though. Turned off Mac in dark mode, booted it in light mode, launched Telegram - it was dark. In settings I had auto-night=system and Dark Mode toggle was on.

This is still the case on version `9.2.1.240459 AppStore`.

**Comment by AlexandruIstrate** [comment]
Still happening in `9.3.241552 AppStore`.

Come on guys, WhatsApp doesn't have this issue. Are you really going to let Zuck be better at these things?

**Comment by Endorphinity** [comment]
This is ridiculous. The issue is still there. Please hire someone able to fix it.

**Comment by Write** [comment]
I really don’t get it, must be trivial to fix.

**Comment by overtake** [comment]
i will check

пн, 16 янв. 2023 г. в 17:41, Endorphinity ***@***.***>:

**Comment by Endorphinity** [comment]
Any news on this issue?

**Comment by Write** [comment]
Yeah LIke seriously? Can't be that hard to implement ?

**Comment by emilismayilov095** [comment]
Same for me

**Comment by overtake** [comment]
Bug occurs after restarting app? If it is i have fixed it today. Fix on the way.

**Comment by emilismayilov095** [comment]
@overtake, yes. Thank you.

**Comment by overtake** [comment]
so. then i can close the issue. thanks

**Comment by panosru** [comment]
@overtake thanks for the fix! In v9.4.1.243742 AppStore the issue is still present, I suppose the fix isn't pushed to AppStore yet, correct?

Thanks!

**Comment by overtake** [comment]
its fixed only in beta. appstore will be released soon

**Comment by Endorphinity** [comment]
> its fixed only in beta. appstore will be released soon

Can you please provide a revision where it is fixed?

**Comment by overtake** [comment]
[Beta version](https://telegram.org/dl/macos/beta)

**Comment by xezrunner** [comment]
> Bug occurs after restarting app? If it is i have fixed it today. Fix on the way.

To clarify, the app did not apply the system theme on a cold boot. It did set the new theme, but it would only apply on a second full launch.

I have installed the new beta update and it seems to be fixed. Thank you!

**Comment by Endorphinity** [comment]
As of 9.4.2.243859 Stable, I can confirm it is fixed.

**Comment by benknight** [comment]
Looks like this issue has returned with macOS Tahoe, but only when toggling system theme via Spotlight (as seen below).

<img width="640" height="468" alt="Image" src="https://github.com/user-attachments/assets/801c31f5-3a94-4c45-9275-05d50d95b97d" />
